travis:
  secure:
    BINSTAR_TOKEN: MiiSIVh+TsKHDpLt9Qhscpuuj3ooChqVqNfjOMY6fjK0refXFKlPw/HJHApob9CsiK7nXNwIM32YKU7JS2rlyZNOR+e77WuEJD/0L28AXlz1DphiC/py4mdl0QjUxNeC1e/PGnH6Fu3+/cHMGyTIMKjb1kDMS9m+W8muB8eyKzgaS8D/EY3O2a9YYz7D0Erxjvkray9lXqz9b7IvcoE2oBnFmJVmFPiUNdNUMMuYzgcMPldQyR/fWsJitOy6sR9tAMK69OpWMqewr7sB+VTaje2BsLQ/O8ioXWiJDMZMwMTHw61ibSAw9kqiQiMK84dI4h79gZMrDHjXXOkp9yonUwsR0TVYxIliab5Cp6H696Fd/o6i8MRMDpuURUdXfKosaw6ESHGZpaLLiGT9NmXTemZJHXaZ5P7X+k7M8IBp8l1Ll+aLGr8hs1bKLIGhiNeG7VdvRUOjoh4Br8mCkM8xWEYgBesG+Y0fs4SfZOGsF877kO8up6dT0aycmflmU+eecs0wNuLOLqPC0E9hZFy0BTsIMJPHGN5F+fhqOWGsUamTASQ3fMDtZpPIYjN1IiLc6V2eUUw7mk1RlXFjSErY077+4F63B91lzhOQ5CrHdmsoZt9ihEO2PiqKPAgW0Ipq3HwG59IhsFQIVqOVUWJIN97NWYXQt0+rGUU4htsmspM=
bot:
  automerge: true
conda_forge_output_validation: true
